name: Test

on:
  workflow_dispatch:
    inputs:
      normalised-branch-name:
        description: "Normalised branch name to cleanup"
        required: true
  push:

jobs:
  prerequisites:
    runs-on: ubuntu-latest
    name: Prerequisites

    steps:
      - name: "Checking out from GitHub"
        uses: "actions/checkout@v2"

      - name: Get normalised branch name
        id: normaliseBranchName
        run: |
          outputName=$(if [[ -z ${{ github.event.inputs.normalised-branch-name }} ]]; then echo "${{ github.event.inputs.normalised-branch-name }}" else echo "${{ github.event.ref }}"; fi)
          echo "::set-output name=normalisedBranchName::$outputName

    outputs:
      normalisedBranchName: ${{ steps.normaliseBranchName.outputs.normalisedBranchName }}

  get-outputs:
    runs-on: ubuntu-latest
    name: Outputs
    needs: prerequisites

    steps:
      - name: Log output
        run: echo ${{ needs.prerequisites.outputs.normalisedBranchName }}
