name: Test

on:
  workflow_dispatch:
    inputs:
      normalised-branch-name:
        description: "Normalised branch name to cleanup"
        required: true
  push:

jobs:
  prerequisites:
    runs-on: ubuntu-latest
    name: Prerequisites

    steps:
      - name: "Checking out from GitHub"
        uses: "actions/checkout@v2"

      - name: Get normalised branch name
        id: normaliseBranchName
        env:
          MANUAL_INPUT: ${{ github.event.inputs.normalised-branch-name }}
          BRANCH_NAME: ${{ github.event.ref }}
        run: |
          outputName=$(if [[ $MANUAL_INPUT ]]; then echo "$MANUAL_INPUT"; else echo "$BRANCH_NAME"; fi)
          echo "::set-output name=normalisedBranchName::$outputName"

    outputs:
      normalisedBranchName: ${{ steps.normaliseBranchName.outputs.normalisedBranchName }}

  get-outputs:
    runs-on: ubuntu-latest
    name: Outputs
    needs: prerequisites

    steps:
      - name: Log output
        run: echo ${{ needs.prerequisites.outputs.normalisedBranchName }}
